config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  namespace :admins do
    resources :tags
    resources :items do
      member do
        patch 'soldout'
        patch 'fix'
        delete 'delete_image'
      end
      get "order_index", on: :collection
    end
  end
  # ここに、how_to_useのルーティングを追加する
  post '/add_item', to: 'carts#add_item'
  root 'items#index'
  get '/how_to_use', to: 'how_to_use#index'
  resources :items, param: :id
  resources :categories
  resources :carts do
    member do
      get 'confirm_order'
      post 'place_order'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/admin.rb
# frozen_string_literal: true

# Adminクラスは管理者用のモデルです。
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecordはActiveRecord::Baseを継承したベースモデルです。
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
# frozen_string_literal: true

# cartモデル
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :orders
  has_many :items, through: :cart_items
end

app/models/cart_item.rb
# frozen_string_literal: true

# cart_itemモデル
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/category.rb
# frozen_string_literal: true

# categoryモデル
class Category < ApplicationRecord
  has_many :items # itemによって所有されているということを意味する
end

app/models/item.rb
# frozen_string_literal: true

# itemモデル
class Item < ApplicationRecord
  include AASM
  aasm do
    state :unreserved, initial: true
    state :reserved
    state :sold

    event :reserve do
      transitions from: :unreserved, to: :reserved
    end

    event :cancel do
      transitions from: :reserved, to: :unreserved
    end

    event :soldout do
      transitions from: :reserved, to: :sold
    end

    event :fix do
      transitions from: :sold, to: :unreserved
    end
  end
  belongs_to :category
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :order_items
  has_many :orders, through: :order_items
  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags
  validates :name, presence: true
  validates :description, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 9_999_999 },
                    format: { with: /\A\d+(\.\d{1,2})?\z/ }
  scope :price_asc, -> { order(price: :asc) }
  scope :price_desc, -> { order(price: :desc) }
  scope :new_item, -> { order(created_at: :desc) }
  has_many_attached :images ,dependent: :destroy
  accepts_nested_attributes_for :images_attachments, allow_destroy: true
  validates :images, attached: true, content_type: %w[image/png image/jpg image/jpeg], size: { less_than: 10.megabytes }
end

app/models/item_tag.rb
class ItemTag < ApplicationRecord
    belongs_to :item
    belongs_to :tag
end

app/models/order.rb
# frozen_string_literal: true

# orderモデル
class Order < ApplicationRecord
  belongs_to :cart, optional: true
  has_many :order_items
  has_many :items, through: :order_items
end

app/models/order_item.rb
# frozen_string_literal: true

# order_itemモデル
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :item_tags, dependent: :destroy
    has_many :items, through: :item_tags
    validates :name, presence: true, uniqueness: true

    
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# application_controller
class ApplicationController < ActionController::Base
  before_action :config_permitted_parameters, if: :devise_controller?
  helper_method :current_cart
  def after_sign_in_path_for(_admin)
    admins_items_path
  end
  private

  # セッションの作成
  def current_cart
    # セッションから取得したcart_idを元にCartテーブルからCart情報を取得
    current_cart = Cart.find_by(id: session[:cart_id])
    # Cart情報が存在しない場合、@current_cartを作成
    current_cart ||= Cart.create
    # 取得したCart情報よりIDを取得し、セッションに設定
    session[:cart_id] = current_cart.id
    # Cart情報を返却
    current_cart
  end
  
  def config_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up)
    devise_parameter_sanitizer.permit(:account_update)
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

# cart_controller
class CartsController < ApplicationController
  before_action :set_line_item, only: [:add_item]
  before_action :set_cart, only: %i[confirm_order place_order add_item]

  def show
    @cart_items = current_cart.cart_items
  end

  def confirm_order
    @cart = current_cart.cart_items
    @order = Order.new
  end

  def create
    @items = current_cart.items.all
    @cart_items = current_cart.cart_items
    @order = current_cart.orders.new(order_params)
    if @items.all? { |item| item.aasm_state == 'unreserved' }
      if @order.save!
        # 注文が確定したので、itemのreservedカラムを更新する
        @items.each do |item|
          OrderItem.create(item_id: item.id, order_id: @order.id, price: item.price)
          item.reserve
          item.save
        end
        @cart_items.destroy_all
        AdminMailer.order_email(@order).deliver_now
        redirect_to root_path, notice: 'You reserved!'
      else
        render :confirm_order
      end
    else
      redirect_to cart_path(current_cart), notice: 'Some items are already reserved.'
    end
  end

  def add_item
    @cart_item = @cart.cart_items.build(item_id: params[:item_id]) if @cart_item.blank?
    @cart_item.quantity = params[:quantity].to_i # quantityの量をパラメーターとして受け取ったら、それをcart_itemのquantityとして、認識する。
    if @cart_item.save
      redirect_to current_cart
    else
      redirect_to controller: 'items', action: 'show'
    end
  end

  def edit; end

  def update; end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash[:success] = 'Delete the items'
    redirect_to cart_path
  end

  private

  def set_line_item
    @cart_item = current_cart.cart_items.find_by(item_id: params[:item_id])
  end

  def set_cart
    @cart = current_cart
  end

  def order_params
    params.require(:order).permit(:name, :phone_number, :address, :cart_id)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# category_controller
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def edit; end

  def show
    @category = Category.find(params[:id])
    @items = @category.items
    
    if params[:tags].present?
      @items = @items.joins(:tags).where(tags: { id: params[:tags] })
    end
    
    if params[:price_desc]
      @items = @items.order(price: :desc)
    elsif params[:price_asc]
      @items = @items.order(price: :asc)
    end
    
    @items = @items.page(params[:page]).per(15)
  end

end

app/controllers/how_to_use_controller.rb
class HowToUseController < ApplicationController
    def index
    end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

# item_controller
class ItemsController < ApplicationController
  def index
    @tops_item = Item.where(category_id: 1).last(3)
    @bottoms_item = Item.where(category_id: 2).last(3)
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        @index = Tag.all
    end
end

app/helpers/admins/tags_helper.rb
module Admins::TagsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# application_helper
module ApplicationHelper
  # ページごとの完全なタイトルを返します
  def full_title(page_title = '')
    # メソッド定義とオプション引数
    base_title = 'Rwanda Shopping' # 変数への代入
    if page_title.empty? # 論理値テスト
      base_title # 暗黙の戻り値
    else
      "#{page_title} | #{base_title}" # 文字列の結合
    end
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

# cart_helper
module CartsHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

# category_helper
module CategoriesHelper
end

app/helpers/how_to_use_helper.rb
module HowToUseHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

# item_helper
module ItemsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/carts/confirm_order.html.erb
<%= form_with(model: @order, url: carts_path(@cart), method: :post, local: true, html: { class: 'needs-validation', novalidate: '' }) do |f| %>

  <div class="mb-3">
    <%= f.label :name, 'name', class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control', required: true %>
    <div class="invalid-feedback">
      confirm your name
    </div>
  </div>

  <div class="mb-3">
    <%= f.label :phone_number, 'phone-number', class: 'form-label' %>
    <%= f.text_field :phone_number, class: 'form-control', required: true %>
    <div class="invalid-feedback">
      confirm phone number
    </div>
  </div>
  <%= f.submit 'submit', class: 'btn btn-primary' %>
<% end %>

<script type="text/javascript">
  window.addEventListener('popstate', function(event) {
    location.reload();
  });
</script>

app/views/carts/show.html.erb
<div class="low">
  <div class="col">
    <h1>Your favorite items</h1>
  </div>
 </div>
 <% if @cart_items.any? %>
  <section class="h-100 gradient-custom">
    <div class="container py-5">
      <div class="row d-flex justify-content-center my-4">
        <div class="col-md-8">
          <div class="card mb-4">
            <div class="card-header py-3">
              <h5 class="mb-0">Cart - <%=@cart_items.count%> items</h5>
            </div>
            <div class="card-body">
            <% @cart_items.each do |cart_item| %>
              <!-- Single item -->
              <div class="row">
                <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                  <!-- Image -->
                  <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                    <%= image_tag cart_item.item.images.first.variant(resize_to_fill: [2000,2000]).processed,class:"w-100" %>
                    <a href="#!">
                      <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                    </a>
                  </div>
                  <!-- Image -->
                </div>

                <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                  <!-- Data -->
                  <p><strong><%= cart_item.item.name %></strong></p>
                  <p>sex:<%= cart_item.item.category.name %> </p>
                    <%= button_to cart_path(cart_item),class:"btn btn-primary btn-sm me-1 mb-2", method: :delete do %>

                    <i class="fas fa-trash"></i>remove
                    <% end %>
                  <!-- Data -->
                  <p>
                    <% if cart_item.item.reserved? %>
                      
                    <% else %>

                    <% end %>
                  </p>
                </div>

                <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                  
                  <!-- Price -->
                  <p class="text-start text-md-center">
                    <strong>$<%= cart_item.item.price %></strong>
                  </p>
                  <!-- Price -->
                </div>
              </div>
              <!-- Single item -->
              <hr class="my-4" />
            <% end %> 

            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-header py-3">
              <h5 class="mb-0">Summary</h5>
            </div>
            <div class="card-body">
              <ul class="list-group list-group-flush"> 
                <li
                  class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                  <div>
                    <strong>Total price</strong>
                  </div>
                  <span><strong>$<%= @cart_items.sum { |cart_item| cart_item.item.price } %></strong></span>
                </li>
              </ul>
              <% if @cart_items.all? { |cart_item| cart_item.item.reserved? } %>
                <div class="alert alert-danger" role="alert">
                  It is already reserved and cannot be added.
                </div>
              <% else %>
                <%= button_to "reserve", confirm_order_cart_path(@cart_items), method: :get, class: "btn btn-primary" %>
              <% end %>
                </div>
          </div>
        </div>
      </div>
    </div>
  </section>


<% else %>
  <p>Your favorite item is enpty</p>
<% end %>



app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/show.html.erb
<%provide(:title,@category.name)%>
<div class="row pt-2 pb-2">
  <div class="col Item-title">
    <h1><%= @category.name %></h1>
  </div>
</div>
<div class="row">   
    <%= form_with(url: category_path(@category), method: :get, local: true, class: 'my-3') do %>
      <div class="col d-flex flex-wrap">
        <% Tag.all.each do |tag| %>
          <div class="form-check mb-2 me-3">
            <%= check_box_tag 'tags[]', tag.id, params[:tags]&.include?(tag.id.to_s), class: 'form-check-input' %>
            <%= label_tag "tags_#{tag.id}", tag.name, class: 'form-check-label' %>
          </div>
        <% end %>
            <%= submit_tag 'Filter', class: 'btn btn-primary' %>
      </div>
    <% end %>
    <div class="col pt-2 dropdown  d-flex justify-content-end">
      <a class="btn btn-outline-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
        Sort
      </a>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <li><%= link_to 'Low-price', category_path(price_asc: "true"), class:"dropdown-item" %></li>
        <li><%= link_to 'High-price', category_path(price_desc: "true"), class:"dropdown-item" %></li>
        <li><%= link_to 'latest', category_path(new_item: "true"), class:"dropdown-item" %></li>
      </ul>
    </div>
  </div>
<div class="row row-cols-1 row-cols-md-3 g-4 pt-3"> 
  <% @items.each do|item| %>
    <div class="col-4 col-md-6 col-lg-4 px-0">
      <div class="card h-100"> 
        <%= image_tag item.images.first.variant(resize_to_fill: [400, 400]).processed,class:"card-img-top p-0" %>
        <div class="card-body">
          <div class="product-price-index pb-4 text-success"><span><%=item.price%>$</span></div>  
          <%= link_to("show", item_path(item), {class: "btn btn-primary stretched-link"}) %>
        </div>
      </div>
    </div>
  <% end %>
</div> 
<%= paginate @items, theme: 'bootstrap-5' %>