config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  namespace :admins do
    resources :tags
    resources :items do
      member do
        patch 'soldout'
        patch 'fix'
        delete 'delete_image'
      end
      get "order_index", on: :collection
    end
  end
  # ここに、how_to_useのルーティングを追加する
  post '/add_item', to: 'carts#add_item'
  root 'items#index'
  get '/how_to_use', to: 'how_to_use#index'
  resources :items, param: :id
  resources :categories
  resources :carts do
    member do
      get 'confirm_order'
      post 'place_order'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/item.rb
# frozen_string_literal: true

# itemモデル
class Item < ApplicationRecord
  include AASM
  aasm do
    state :unreserved, initial: true
    state :reserved
    state :sold

    event :reserve do
      transitions from: :unreserved, to: :reserved
    end

    event :cancel do
      transitions from: :reserved, to: :unreserved
    end

    event :soldout do
      transitions from: :reserved, to: :sold
    end

    event :fix do
      transitions from: :sold, to: :unreserved
    end
  end
  belongs_to :category
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :order_items
  has_many :orders, through: :order_items
  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags
  validates :name, presence: true
  validates :description, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 9_999_999 },
                    format: { with: /\A\d+(\.\d{1,2})?\z/ }
  scope :price_asc, -> { order(price: :asc) }
  scope :price_desc, -> { order(price: :desc) }
  scope :new_item, -> { order(created_at: :desc) }
  has_many_attached :images ,dependent: :destroy
  accepts_nested_attributes_for :images_attachments, allow_destroy: true
  validates :images, attached: true, content_type: %w[image/png image/jpg image/jpeg], size: { less_than: 10.megabytes }
end

app/controllers/admins/items_controller.rb
# frozen_string_literal: true

# Admins::ItemsControllerに関する説明や機能などを記述する
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_item, only: %i[edit update destroy]
  
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.images.attach(params[:item][:images]) if params[:item][:images].present?
    if @item.save
      flash[:success] = 'Adding item is Successful'
      redirect_to admins_items_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @item.images.attach(params[:item][:images]) if params[:item][:images].present?
    if @item.update(item_params)
      flash[:success] = 'Success'
      redirect_to admins_items_path
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id]).destroy
    flash[:success] = 'item deleted'
    redirect_to admins_items_path
  end

  def delete_image
    image = ActiveStorage::Attachment.find(params[:image_id])
    image.purge
    redirect_to edit_admins_item_path(params[:id]), notice: 'Image was successfully deleted.'
  end

  def soldout
    @item = Item.find(params[:id])
    @item.soldout!
    @item.save
    redirect_to edit_admins_item_path(@item), notice: 'Item is now sold out.'
  end
  
  def fix
    @item = Item.find(params[:id])
    @item.fix!
    @item.save
    redirect_to edit_admins_item_path(@item), notice: 'Item is now unreserved'
  end

  def order_index
    @orders_by_date = Order.all.group_by { |order| order.created_at.to_date }
    @orders_by_date = @orders_by_date.sort_by { |date, _orders| date }.reverse.to_h
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :price, :size, :status, :category_id, :quantity, tag_ids:[], images_attachments_attributes: [ :id, :_destroy ])
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

# item_controller
class ItemsController < ApplicationController
  def index
    @tops_item = Item.where(category_id: 1).last(3)
    @bottoms_item = Item.where(category_id: 2).last(3)
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/helpers/admins/items_helper.rb
# frozen_string_literal: true

# admin_item_helper
module Admins::ItemsHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

# item_helper
module ItemsHelper
end

app/views/admins/items/edit.html.erb
<div class="col-12">
      <% if @item.reserved? %>
        <%= button_to 'Sold Out', soldout_admins_item_path(@item), method: :patch, class: 'btn btn-primary' %>
      <% elsif @item.sold? %>
        <%= button_to 'fix to unreserved', fix_admins_item_path(@item), method: :patch, class: 'btn btn-primary' %>
      <% end %>
</div>
<%= form_with model:@item,url:admins_item_path do |f|%>
 <%= render 'shared/error_messages' %>
 <form>
 <div class="row g-3">
  <div class="col-md-6">
     <%= f.label :name,class:"form-label"%>
     <%= f.text_field :name, class: "form-control",placeholder: "Enter item name"%>
  </div>
  <div class="col-md-6">
     <%= f.label :price,class:"form-label"%>
     <%= f.number_field :price , class: "form-control",placeholder: "Enter item price"%>
  </div>
</div>
<div class="row g-3">
  <div class="col-12">
    <%= f.label :description,class:"form-label" %>
    <%= f.text_field :description, class: "form-control",placeholder: "Enter item description",rows:"3" %>
  </div>
  <div class="col-12">
    <%= f.label :category %>
    <%= f.select :category_id, [["boys", 1], ["girls", 2]], include_blank: "select" ,class:"form-control form-select dropdown" %>
  </div>
  <div class="row g-3">
    <div class="col-12">
      <% if @item.images.present? %>
        <div class="edit-preview-images row">
          <% @item.images.each do |image| %>
            <div class="image-block col-4 col-md-6 col-lg-4 px-0">
                <%= image_tag image, class: "w-100 img-fluid" %>
                <%= link_to 'delete' ,delete_image_admins_item_path(image_id: image.id), method: :delete, class: 'btn btn-danger'%>
            </div>
          <% end %>
        </div>
        <%= f.label :images,"Item Images", class:"form-label" %>
      <div id="image-box-1">
        <div class="item-num-0" id="image-box_container">
          <%= f.fields_for :images do |i| %>
            <div class="preview-image-box">
                <div class="d-flex row" id="preview-image-box">
                  <label class="w-50" for="img-file">
                    <i class="fa fa-plus-circle add-image-icon justify-content-center d-flex h3" aria-hidden="true"></i>
                  </label>
                </div>
                <%= f.file_field :images,multiple: true, id: "img-file",style: "display: none;" %>
                  <div class="preview-image w-50" id="image-preview-container" style: "display: none;"></div>    
              </div>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <div class="col-12">
    <%= f.label :tags, "Item Tags", class:"form-label" %>
    <div class="row">
      <% Tag.all.each do |tag| %>
        <div class="col-3">
          <%= check_box_tag "item[tag_ids][]", tag.id, @item.tags.include?(tag), id: "item_tag_ids_#{tag.id}" %>
          <%= label_tag "item_tag_ids_#{tag.id}", tag.name %>
        </div>
      <% end %>
    </div>
  </div> 
</div>
  <div class="col-12">
    <button type="submit" class="btn btn-primary">item add</button>
  </div>
</form>
<% end %>
<%= button_to admins_item_path(@item.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', form: { class: 'd-inline' } do %>
  Delete
<% end %>

<script>
$(function(){
  var dataBox = new DataTransfer();
  var file_field = document.querySelector('input[type=file]')
  $('#img-file').change(function(){
    var files = $('input[type="file"]').prop('files')[0];
    $.each(this.files, function(i, file){
      var fileReader = new FileReader();
      dataBox.items.add(file)
      file_field.files = dataBox.files

      var num = $('.item-image').length + 1 + i
      fileReader.readAsDataURL(file);
      if (num == 10){
        $('#image-box_container').css('display', 'none')   
      }
      fileReader.onloadend = function() {
        var src = fileReader.result
        var html= `<div class='image-block item-image col-4 col-md-6 col-lg-4 px-0' data-image="${file.name}">
                    <div class='item-image_content'>
                      <div class='item-image_content-icon'>
                        <img src=${src} class="w-100">
                      </div>
                    </div>
                    <div class='item-image_operetion'>
                      <div class='btn btn-danger item-image_operetion-delete'>削除</div>
                    </div>
                  </div>`
        $('#preview-image-box').prepend(html);
      };
      $('#image-box_container').attr('class', `item-num-${num}`)
    });
  });
  $(document).on("click", '.item-image_operetion-delete', function(){
    var target_image = $(this).closest('.item-image');
    target_image.remove();
    file_field.val("");
  });
});
</script>

app/views/admins/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <h2>Admin Item-page</h2>
    </div>
    <div class="col-sm-4 text-sm-end">
      <%= link_to("add item", new_admins_item_path, {class: "btn btn-outline-primary View-All-button"}) %>
      <%= link_to 'Order', order_index_admins_items_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>
<div class="container mt-4">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">name</th>
          <th scope="col">price</th>
          <th scope="col">category</th>
          <th scope="col">state</th>
          <th scope="col">tags</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= item.price %></td>
          <td><%= item.category.name %></td>
          <td><%= item.aasm_state %></td>
          <td><%= item.tags.map(&:name).join(', ') %></td>
          <td><%= link_to 'show', item_path(item) %></td><!--items/show.html.erbに飛ぶ。-->
          <td><%= link_to 'edit', edit_admins_item_path(item) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admins/items/new.html.erb
<h2>Item-追加</h2>
<%= form_with model:@item, url:admins_items_path, class:"form-inline" do |f|%>
 <%= render 'shared/error_messages' %>
 <form>
 <div class="row g-3">
  <div class="col-md-6">
     <%= f.label :name, class:"form-label"%>
     <%= f.text_field :name, class: "form-control", placeholder: "Enter item name"%>
  </div>

  <div class="col-md-6">
     <%= f.label :price, class:"form-label"%>
     <%= f.number_field :price, class: "form-control", placeholder: "Enter item price"%>
  </div>

</div>
<div class="row g-3">
  <div class="col-12">
    <%= f.label :description, class:"form-label" %>
    <%= f.text_field :description, class: "form-control", placeholder: "Enter item description", rows:"3" %>
  </div>
  <div class="col-12">
    <%= f.label :category, class:"form-label" %>
    <%= f.select :category_id, [["boys", 1], ["girls", 2]], include_blank: "select" ,class:"form-control form-select dropdown" %>
    <%= f.label :images,"Item Images", class:"form-label" %>
      <div id="image-box-1">
        <div class="item-num-0" id="image-box_container">
          <%= f.fields_for :images do |i| %>
            <div class="preview-image-box">
                <div class="d-flex row" id="preview-image-box">
                  <label class="w-50" for="img-file">
                    <i class="fa fa-plus-circle add-image-icon justify-content-center d-flex h3" aria-hidden="true"></i>
                  </label>
                </div>
                <%= f.file_field :images,multiple: true, id: "img-file",style: "display: none;" %>
                  <div class="preview-image w-50" id="image-preview-container" style: "display: none;"></div>    
              </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-12">
      <%= f.label :tags, "Item Tags", class:"form-label" %>
      <div class="row">
        <% Tag.all.each do |tag| %>
          <div class="col-3">
            <%= check_box_tag "item[tag_ids][]", tag.id, @item.tags.include?(tag), id: "item_tag_ids_#{tag.id}" %>
            <%= label_tag "item_tag_ids_#{tag.id}", tag.name %>
          </div>
        <% end %>
      </div>
    </div>
    
  </div>
  <div class="col-12">
    <button type="submit" class="btn btn-primary">item add</button>
  </div>
</div>
</form>
<% end %>

<script>
$(function(){
  //DataTransferオブジェクトで、データを格納する箱を作る
  var dataBox = new DataTransfer();
  //querySelectorでfile_fieldを取得
  var file_field = document.querySelector('input[type=file]')
  //fileが選択された時に発火するイベント
  $('#img-file').change(function(){
    //選択したfileのオブジェクトをpropで取得
    var files = $('input[type="file"]').prop('files')[0];
    $.each(this.files, function(i, file){
      //FileReaderのreadAsDataURLで指定したFileオブジェクトを読み込む
      var fileReader = new FileReader();

      //DataTransferオブジェクトに対して、fileを追加
      dataBox.items.add(file)
      //DataTransferオブジェクトに入ったfile一覧をfile_fieldの中に代入
      file_field.files = dataBox.files

      var num = $('.item-image').length + 1 + i
      fileReader.readAsDataURL(file);
       //画像が10枚になったら超えたらドロップボックスを削除する
      if (num == 10){
        $('#image-box_container').css('display', 'none')   
      }
      //読み込みが完了すると、srcにfileのURLを格納
      fileReader.onloadend = function() {
        var src = fileReader.result
        var html= `<div class='image-block item-image col-4 col-md-6 col-lg-4 px-0' data-image="${file.name}">
                    <div class='item-image_content'>
                      <div class='item-image_content-icon'>
                        <img src=${src} class="w-100">
                      </div>
                    </div>
                    <div class='item-image_operetion'>
                      <div class='btn btn-danger item-image_operetion-delete'>削除</div>
                    </div>
                  </div>`
        //image_box__container要素の前にhtmlを差し込む
        $('#preview-image-box').prepend(html);
      };
      //image-box__containerのクラスを変更し、CSSでドロップボックスの大きさを変えてやる。
      $('#image-box_container').attr('class', `item-num-${num}`)
    });
  });
  //削除ボタンをクリックすると発火するイベント
  $(document).on("click", '.item-image_operetion-delete', function(){
    //プレビュー要素を取得
    var target_image = $(this).closest('.item-image');
    //プレビューを削除
    target_image.remove();
    //inputタグに入ったファイルを削除
    file_field.val("");
  });
});


</script>

app/views/admins/items/order_index.html.erb
<h1 class="mb-4">Orders Index</h1>

<% @orders_by_date.each do |date, orders| %>
  <h2><%= date %></h2> <!-- 日付を表示 -->

  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Phone Number</th>
          <th scope="col">Cart ID</th>
          <th scope="col">Created At</th>
          <th scope="col">Items</th>
        </tr>
      </thead>
      <tbody>
        <% orders.each do |order| %>
          <tr>
            <th scope="row"><%= order.id %></th>
            <td><%= order.name %></td>
            <td><%= order.phone_number %></td>
            <td><%= order.cart_id %></td>
            <td><%= order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
            <td>
              <ul class="list-unstyled">
                <% order.items.each do |item| %>
                  <li><%= item.name %></li>
                  <li><%= link_to 'show', item_path(item) %></li>
                <% end %>
              </ul>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/admins/items/show.html.erb
<h1>Admins::Toppages#show</h1>
<p>Find me in app/views/admins/toppages/show.html.erb</p>