config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  namespace :admins do
    resources :tags
    resources :items do
      member do
        patch 'soldout'
        patch 'fix'
        delete 'delete_image'
      end
      get "order_index", on: :collection
    end
  end
  # ここに、how_to_useのルーティングを追加する
  post '/add_item', to: 'carts#add_item'
  root 'items#index'
  get '/how_to_use', to: 'how_to_use#index'
  resources :items, param: :id
  resources :categories
  resources :carts do
    member do
      get 'confirm_order'
      post 'place_order'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/item.rb
# frozen_string_literal: true

# itemモデル
class Item < ApplicationRecord
  include AASM
  aasm do
    state :unreserved, initial: true
    state :reserved
    state :sold

    event :reserve do
      transitions from: :unreserved, to: :reserved
    end

    event :cancel do
      transitions from: :reserved, to: :unreserved
    end

    event :soldout do
      transitions from: :reserved, to: :sold
    end

    event :fix do
      transitions from: :sold, to: :unreserved
    end
  end
  belongs_to :category
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :order_items
  has_many :orders, through: :order_items
  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags
  validates :name, presence: true
  validates :description, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 9_999_999 },
                    format: { with: /\A\d+(\.\d{1,2})?\z/ }
  scope :price_asc, -> { order(price: :asc) }
  scope :price_desc, -> { order(price: :desc) }
  scope :new_item, -> { order(created_at: :desc) }
  has_many_attached :images ,dependent: :destroy
  accepts_nested_attributes_for :images_attachments, allow_destroy: true
  validates :images, attached: true, content_type: %w[image/png image/jpg image/jpeg], size: { less_than: 10.megabytes }
end

app/controllers/admins/items_controller.rb
# frozen_string_literal: true

# Admins::ItemsControllerに関する説明や機能などを記述する
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_item, only: %i[edit update destroy]
  
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.images.attach(params[:item][:images]) if params[:item][:images].present?
    if @item.save
      flash[:success] = 'Adding item is Successful'
      redirect_to admins_items_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @item.images.attach(params[:item][:images]) if params[:item][:images].present?
    if @item.update(item_params)
      flash[:success] = 'Success'
      redirect_to admins_items_path
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id]).destroy
    flash[:success] = 'item deleted'
    redirect_to admins_items_path
  end

  def delete_image
    image = ActiveStorage::Attachment.find(params[:image_id])
    image.purge
    redirect_to edit_admins_item_path(params[:id]), notice: 'Image was successfully deleted.'
  end

  def soldout
    @item = Item.find(params[:id])
    @item.soldout!
    @item.save
    redirect_to edit_admins_item_path(@item), notice: 'Item is now sold out.'
  end
  
  def fix
    @item = Item.find(params[:id])
    @item.fix!
    @item.save
    redirect_to edit_admins_item_path(@item), notice: 'Item is now unreserved'
  end

  def order_index
    @orders_by_date = Order.all.group_by { |order| order.created_at.to_date }
    @orders_by_date = @orders_by_date.sort_by { |date, _orders| date }.reverse.to_h
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :price, :size, :status, :category_id, :quantity, tag_ids:[], images_attachments_attributes: [ :id, :_destroy ])
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

# item_controller
class ItemsController < ApplicationController
  def index
    @tops_item = Item.where(category_id: 1).last(3)
    @bottoms_item = Item.where(category_id: 2).last(3)
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/helpers/admins/items_helper.rb
# frozen_string_literal: true

# admin_item_helper
module Admins::ItemsHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

# item_helper
module ItemsHelper
end

app/views/items/_items.html.erb
<% items.each do |item| %>
    <div class="col-4 px-0"> 
        <div class="card h-100">
            <%= image_tag item.images.first.variant(resize_to_fill: [2000, 2000]).processed, class:"card-img-top p-0" %>
            <div class="card-body">
                <p class="card-text text-success fw-bold"><span><%= item.price %>$</span></p>
                <%= link_to("show", item_path(item), {class: "btn btn-primary stretched-link"}) %>
            </div>
        </div>
    </div>
<% end %>

app/views/items/index.html.erb
<%provide(:title,"items")%>

<div class="row pt-2 pb-2">
  <% item=@tops_item.first %>
  <div class="col Item-title">
    <h1><%= item.category.name %></h1>
  </div> 
  <div class="col pt-2">
    <%= link_to("View All", category_path(item.category_id), {class: "btn btn-outline-primary View-All-button"}) %>
  </div>
</div>
<div class="row px-3 pb-2 row-cols-1 row-cols-md-3">
  <%= render 'items', items: @tops_item %>
</div>

<div class="row pt-2 pb-2">
  <% item=@bottoms_item.first %>
  <div class="col Item-title">
    <h1><%= item.category.name %></h1>
  </div> 
  <div class="col pt-2">
    <%= link_to("View All", category_path(item.category_id), {class: "btn btn-outline-primary View-All-button"}) %>
  </div>
</div>
<div class="row px-3 pb-2 row-cols-1 row-cols-md-3">
  <%= render 'items', items: @bottoms_item %>
</div>







app/views/items/show.html.erb
<%provide(:title,"item") %>
<div class="row mt-4">
    <div class="col">
       <div id="wrap">
                  <ul id="slider">
                      <%@item.images.each do |image|%>
                        <li class="slide-item">
                          <%= image_tag image,class:"image-preview" %>
                        </li>
                     <% end %>
                  </ul>
                  <ul id="thumbnail_slider">
                   <%@item.images.each do |image|%>
                      <li class="thumbnail-item">
                        <%= image_tag image %>
                      </li>
                   <% end %>
                  </ul>
            </div>
    </div>
    <div class="col mt-5">
      <div class="title-detail">
        <h2><%= @item.name %></h2>
      </div>
      <div class="product-price">
        <h2 class="text-success"><%= @item.price %>$<h2>
      </div>
        <div class="add-to-cart">
        <% if @item.reserved? || @item.sold? %>
          <div class="alert alert-danger" role="alert">
            It is already reserved and cannot be added.
          </div>
        <% else %>
          <%= form_with url: add_item_path(item_id: @item.id),class:"form-inline" do |form| %>
              <div class="row">
              <%= form.hidden_field :quantity, value: 1 %>
                <div class="col"> 
                  <%= form.submit "Add to Cart",class:"btn btn-primary" %>
                </div>
              </div>
          <% end %>
        <% end %>
        <div class="col">
          <% if admin_signed_in? %>
            <% if @item.reserved? %>
              <%= button_to 'Sold Out', soldout_admins_item_path(@item), method: :patch, class: 'btn btn-success' %>
            <% elsif @item.sold? %>
              <%= button_to 'fix to unreserved', fix_admins_item_path(@item), method: :patch, class: 'btn btn-success' %>
            <% end %>
          <% end %>
        </div>            
        </div>          
       </div>  
      </div>
    </div>
</div>
<div class="row">
    <div class="col p-4">
        <h3>description</h3>
        <%= @item.description %>
    </div>   
</div>     
<div class="row mt-4">
  <!--プレビューの写真を全画面表示-->
    <div class="modal">
      <span class="close">&times;</span>
      <img src="" alt="" class="modal-content">
      <div id="caption"></div>
    </div>
  </div>
  </div>



<script type="text/javascript">
// 画像をクリックしたときにモーダルウィンドウを表示するイベントを設定
var images = document.getElementsByClassName("image-preview");
var modal = document.getElementsByClassName("modal")[0];
var modalImg = document.getElementsByClassName("modal-content")[0];
var captionText = document.getElementById("caption");

for (var i = 0; i < images.length; i++) {
  images[i].addEventListener("click", function() {
    modal.style.display = "block";
    modalImg.src = this.src;
    captionText.innerHTML = this.alt;
  });
}

// モーダルウィンドウの×印をクリックしたときにモーダルウィンドウを閉じるイベントを設定
var close = document.getElementsByClassName("close")[0];
close.addEventListener("click", function() {
  modal.style.display = "none";
});

$(function() {
  var $mainImage = $('.main-image img');
  var $thumbnailImages = $('.thumbnail-images img');

  $thumbnailImages.on('click', function() {
    var imageUrl = $(this).attr('src');
    $mainImage.attr('src', imageUrl);
  });
});

modal.style.display = "none";
close.addEventListener("click", function() {
  modal.style.display = "none";
});


  $(function(){
 var mainSlider = "#slider"; //メインスライダーid
 var thumbnailSlider = "#thumbnail_slider"; //サムネイルスライダーid
 
  $(mainSlider).slick({
    autoplay: true,
    speed: 1000,
    arrows: false,
    asNavFor: thumbnailSlider
  });
  $(thumbnailSlider).slick({
    slidesToShow: 3,
    speed: 1000,    
    asNavFor: mainSlider
  });
  //#thumbnail_sliderでクリックしたスライドをカレントにする
  $(thumbnailSlider+" .slick-slide").on('click',function(){
    var index = $(this).attr("data-slick-index");
    $(thumbnailSlider).slick("slickGoTo",index,false);
  });
});
</script>