config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  namespace :admins do
    resources :tags
    resources :items do
      member do
        patch 'soldout'
        patch 'fix'
        delete 'delete_image'
      end
      get "order_index", on: :collection
    end
  end
  # ここに、how_to_useのルーティングを追加する
  post '/add_item', to: 'carts#add_item'
  root 'items#index'
  get '/how_to_use', to: 'how_to_use#index'
  resources :items, param: :id
  resources :categories
  resources :carts do
    member do
      get 'confirm_order'
      post 'place_order'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/admin.rb
# frozen_string_literal: true

# Adminクラスは管理者用のモデルです。
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecordはActiveRecord::Baseを継承したベースモデルです。
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
# frozen_string_literal: true

# cartモデル
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :orders
  has_many :items, through: :cart_items
end

app/models/cart_item.rb
# frozen_string_literal: true

# cart_itemモデル
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/category.rb
# frozen_string_literal: true

# categoryモデル
class Category < ApplicationRecord
  has_many :items # itemによって所有されているということを意味する
end

app/models/item.rb
# frozen_string_literal: true

# itemモデル
class Item < ApplicationRecord
  include AASM
  aasm do
    state :unreserved, initial: true
    state :reserved
    state :sold

    event :reserve do
      transitions from: :unreserved, to: :reserved
    end

    event :cancel do
      transitions from: :reserved, to: :unreserved
    end

    event :soldout do
      transitions from: :reserved, to: :sold
    end

    event :fix do
      transitions from: :sold, to: :unreserved
    end
  end
  belongs_to :category
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :order_items
  has_many :orders, through: :order_items
  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags
  validates :name, presence: true
  validates :description, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 9_999_999 },
                    format: { with: /\A\d+(\.\d{1,2})?\z/ }
  scope :price_asc, -> { order(price: :asc) }
  scope :price_desc, -> { order(price: :desc) }
  scope :new_item, -> { order(created_at: :desc) }
  has_many_attached :images ,dependent: :destroy
  accepts_nested_attributes_for :images_attachments, allow_destroy: true
  validates :images, attached: true, content_type: %w[image/png image/jpg image/jpeg], size: { less_than: 10.megabytes }
end

app/models/item_tag.rb
class ItemTag < ApplicationRecord
    belongs_to :item
    belongs_to :tag
end

app/models/order.rb
# frozen_string_literal: true

# orderモデル
class Order < ApplicationRecord
  belongs_to :cart, optional: true
  has_many :order_items
  has_many :items, through: :order_items
end

app/models/order_item.rb
# frozen_string_literal: true

# order_itemモデル
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :item_tags, dependent: :destroy
    has_many :items, through: :item_tags
    validates :name, presence: true, uniqueness: true

    
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

# cart_controller
class CartsController < ApplicationController
  before_action :set_line_item, only: [:add_item]
  before_action :set_cart, only: %i[confirm_order place_order add_item]

  def show
    @cart_items = current_cart.cart_items
  end

  def confirm_order
    @cart = current_cart.cart_items
    @order = Order.new
  end

  def create
    @items = current_cart.items.all
    @cart_items = current_cart.cart_items
    @order = current_cart.orders.new(order_params)
    if @items.all? { |item| item.aasm_state == 'unreserved' }
      if @order.save!
        # 注文が確定したので、itemのreservedカラムを更新する
        @items.each do |item|
          OrderItem.create(item_id: item.id, order_id: @order.id, price: item.price)
          item.reserve
          item.save
        end
        @cart_items.destroy_all
        AdminMailer.order_email(@order).deliver_now
        redirect_to root_path, notice: 'You reserved!'
      else
        render :confirm_order
      end
    else
      redirect_to cart_path(current_cart), notice: 'Some items are already reserved.'
    end
  end

  def add_item
    @cart_item = @cart.cart_items.build(item_id: params[:item_id]) if @cart_item.blank?
    @cart_item.quantity = params[:quantity].to_i # quantityの量をパラメーターとして受け取ったら、それをcart_itemのquantityとして、認識する。
    if @cart_item.save
      redirect_to current_cart
    else
      redirect_to controller: 'items', action: 'show'
    end
  end

  def edit; end

  def update; end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash[:success] = 'Delete the items'
    redirect_to cart_path
  end

  private

  def set_line_item
    @cart_item = current_cart.cart_items.find_by(item_id: params[:item_id])
  end

  def set_cart
    @cart = current_cart
  end

  def order_params
    params.require(:order).permit(:name, :phone_number, :address, :cart_id)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# category_controller
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def edit; end

  def show
    @category = Category.find(params[:id])
    @items = @category.items
    
    if params[:tags].present?
      @items = @items.joins(:tags).where(tags: { id: params[:tags] })
    end
    
    if params[:price_desc]
      @items = @items.order(price: :desc)
    elsif params[:price_asc]
      @items = @items.order(price: :asc)
    end
    
    @items = @items.page(params[:page]).per(15)
  end

end

app/controllers/items_controller.rb
# frozen_string_literal: true

# item_controller
class ItemsController < ApplicationController
  def index
    @tops_item = Item.where(category_id: 1).last(3)
    @bottoms_item = Item.where(category_id: 2).last(3)
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        @index = Tag.all
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# application_helper
module ApplicationHelper
  # ページごとの完全なタイトルを返します
  def full_title(page_title = '')
    # メソッド定義とオプション引数
    base_title = 'Rwanda Shopping' # 変数への代入
    if page_title.empty? # 論理値テスト
      base_title # 暗黙の戻り値
    else
      "#{page_title} | #{base_title}" # 文字列の結合
    end
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

# cart_helper
module CartsHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

# category_helper
module CategoriesHelper
end

app/helpers/how_to_use_helper.rb
module HowToUseHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

# item_helper
module ItemsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(resource.errors.count, "error") %> prohibited this admin from being saved:</h2>

    <ul>
    <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-top">
  <div class="container">
    <h3><%= link_to("rwanshop", root_path,class:"navbar-brand text-white pt-1")%></h3>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to("Home", root_path,class:"nav-link")%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to("boys", category_path(1),{class:"dropdown-item"}) %></li>
            <li><%= link_to("girls", category_path(2),{class:"dropdown-item"}) %> </li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to("How to use", how_to_use_path ,class:"nav-link")%>
        </li>
      </ul>
      <div class="d-flex">
        <%= link_to("Your favorite", cart_path(current_cart.id),class:"nav-link" )%>
      </div>
    </div>
  </div>
</nav>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/bc40bbfeb0.js" crossorigin="anonymous"></script>
    <!----- ビューポート---------->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!----- ここから、CDN---------->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
   <%= render 'layouts/header' %>
   <div class="container">
     <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    </div>
   <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @item.errors.any? %><!--@user newした後、errorがあったとき。これはもとからrails に備わる機能-->
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@item.errors.count, "error") %><!--pluralizeは英語の文法直しの役割-->
    </div>
    <ul>
    <% @item.errors.full_messages.each do |msg| %><!--errors.full_messagesもrailsに備わる機能-->
      <li><%= msg %></li><!--エラーメッセージを表示-->
    <% end %>
    </ul>
  </div>
<% end %>